import React from "react";
import Image from "../Image.png";

const Circle = ({scales, renderMusic}) => {

  return (
    <div>
      {/* Image Map Generated by http://www.image-map.net/ */}
      <img src={Image} useMap="#image-map" alt="Circle of Fifths" />
      <map name="image-map">
        {scales.map((scale, index) => {
          return (
            <area
              key={index}
              onClick={(e) => renderMusic(e, scale)}
              alt={scale.alt}
              title={scale.title}
              coords={scale.coords}
              shape={scale.shape}
            ></area>
          );
        })}
      </map>
    </div>
  );
};

export default Circle;
