import React from "react";
import Image from "../Image.png";

const Circle = ({scales}) => {
  const renderMusic = (e, scale) => {
    e.preventDefault();
    console.log(scale.src)
    // return (
    //   <div id="flat-io">
    //     <iframe
    //       src={scales.src}
    //       height="600"
    //       width="100%"
    //       frameBorder="0"
    //       allowfullscreen
    //       allow="midi"
    //     ></iframe>
    //   </div>
    // );
  };

  return (
    <div>
      {/* Image Map Generated by http://www.image-map.net/ */}
      <img src={Image} useMap="#image-map" alt="Circle of Fifths" />
      <map name="image-map">
        {scales.map((scale, index) => {
          return (
            <area
              key={index}
              onClick={(e) => renderMusic(e, scale)}
              alt={scale.alt}
              title={scale.title}
              href={scale.href}
              coords={scale.coords}
              shape={scale.shape}
            ></area>
          );
        })}
      </map>
    </div>
  );
};

export default Circle;
